---
booktitle: 'Proceedings of the AAAI 2026 Workshop on Audio-Centric AI: Towards
  Real-World Multimodal Reasoning and Application Use Cases (Audio-AAAI)'
shortname: Audio-AAAI
year: '2026'
volume: '312'
start: &1 2026-01-26
end: 2026-01-26
published: 2026-02-27
conference_number: '1'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: AUDIO-AAAI2026
month: 0
cycles: false
bibtex_editor: Komatsu, Tatsuya and Imoto, Keisuke and Gao, Xiaoxue and Ono, Nobutaka
  and Chen, Nancy F.
editor:
- given: Tatsuya
  family: Komatsu
- given: Keisuke
  family: Imoto
- given: Xiaoxue
  family: Gao
- given: Nobutaka
  family: Ono
- given: Nancy F.
  family: Chen
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the AAAI 2026 Workshop on Audio-Centric AI: Towards Real-World Multimodal Reasoning and Application Use Cases (Audio-AAAI)
    Held in Singapore EXPO, Singapore, Singapore on 26 January 2026

  Published as Volume 312 by the Proceedings of Machine Learning Research on 27 February 2026.

  Volume Edited by:
    Tatsuya Komatsu
    Keisuke Imoto
    Xiaoxue Gao
    Nobutaka Ono
    Nancy F. Chen

  Series Editors:
    Neil D. Lawrence
date_str: 26 Jan
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v312"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v312
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v312
email: ''
conference:
  name: 'Audio-Centric AI: Towards Real-World Multimodal Reasoning and Application
    Use Cases (Audio-AAAI)'
  url: https://sites.google.com/view/audio-aaai
  location: Singapore EXPO, Singapore, Singapore
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: audio-aaai26_clean.bib
# Site settings
# Original source:  audio-aaai26_clean.bib
